[package]
name = "skopos"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.13.1"
tonic-reflection = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
